### ISSUE TITLE
Command-line support

### ISSUE THREAD

**Issue by IS4Code** [stascorp/MIDIPLEX#2]
Is adding command-line support for quick conversions between formats possible? This is the only Windows program I know that can convert MDI.

**Comment by binarymaster** [comment]
Good idea! I'll implement this in future release.

**Comment by CDWimmer** [comment]
Hey, trying this out with the pre-release. Tried the following:
`MIDIPLEX.exe "C:\some\path\STEADY.XMI" -c midi steady.mid`

It opened the UI with the file loaded, but did not otherwise save the file as I had hoped it would. This is the only software for converting XMIs that anyone seems to think is any good that runs on modern platforms, and I'd really like to be able to process a bunch of files programmatically without having to go through the UI each time. Would this be possible to look at? (appreciate it has been a decade!)
